### ISSUE TITLE
New right aligned drawer

### ISSUE THREAD

**Issue by oppiliappan** [thermatk/FastHub#37] opened 2018-03-08 01:29 UTC
**FastHub-Libre Version: 4.6.3**  
**Android Version: 8.1.0 (SDK: 27)**  
**Device Information:**  
- **Manufacturer:** LGE  
- **Brand:** lge  
- **Model:** Nexus 5  
---

The scroll bar interferes with the new drawer.  
Pulling out the drawer makes me scroll down through my feed.

Maybe we can implement a different way to access this drawer?

**Comment by thermatk** [comment] 2018-03-21 18:46
confirmed, duplicate of #35

**Closed as completed by thermatk** 2018-03-21 18:46 UTC

**Comment by thermatk** [comment] 2018-03-29 19:30
fixed
